### ISSUE TITLE
Suggestions for the profiles folder

### ISSUE THREAD

**Issue by hartwork** [anomen-s/anomen-overlay#2]
Hi!

Looking at the `profiles` folder I found
- two null byte files (`categories` and `package.mask`) and
- one file (`use.local.desc` ) that should not exist (and be generated rather than maintained manually), see https://devmanual.gentoo.org/general-concepts/use-flags/#use-flag-descriptions

Would be cool to have fixed.

Best, Sebastian

**Comment by anomen-s** [comment]
files removed

**Comment by hartwork** [comment]
Excellent, thank you!

56e4ea0cf68068e39de87671b8e3f1936fe803c6
